### PR TITLE
Fixing logic and UI bugs

### LINKED ISSUE #467: Unfriendly error if you don't format your ph number correctly when asking for a box
image

Being a programmer I read this error message and realised there was something wrong with the format of the phone number.

Most users will just see the red and gobbledygook and assume something is broken.

### PR DESCRIPTION
**Pull request by qdozaq**
fixes #467 
This fixes the above bug as well as bunch of other small UI discrepancies and bugs

### CODE REVIEW

File: src/app/component/AddressAutocomplete.jsx [hunk 1]
```diff
@@ -177,6 +178,12 @@ export default function AddressAutocomplete({
     []
   );
 
+  useEffect(() => {
```
Comment (qdozaq) [inline src/app/component/AddressAutocomplete.jsx:181]: This component wasnt updating correctly so added this here

File: src/app/page/Request/RequestPage.jsx [hunk 2]
```diff
@@ -1,16 +1,23 @@
 import React from "react";
-import { Route, Switch } from "react-router-dom";
+import { Route, Switch, useLocation } from "react-router-dom";
```
Comment (qdozaq) [inline src/app/page/Request/RequestPage.jsx:2]: just styling changes for this page

File: src/app/page/Request/Start.jsx [hunk 3]
```diff
@@ -2,22 +2,23 @@ import { Button } from "@material-ui/core";
 import React from "react";
```
Comment (qdozaq) [inline src/app/page/Request/Start.jsx:2]: styling
